-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Sig.dot.

module SigDot.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data DotGraph = GDef GKind ID [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stmt
    = SNode ID [Attr]
    | SEdge ID ID [Attr]
    | SAttr Kind [Attr]
    | SSoloAttr Attr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Attr = ARegular AKind String | AID AKind ID
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AKind
    = AFontsize
    | ARankdir
    | ALabel
    | AColor
    | AFillcolor
    | AStyle
    | AShape
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Kind = KNode | KEgde | KGraph
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GKind = GKDi | GKSub
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype ID = ID String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

